### ISSUE TITLE
numeric question codes & validation

### ISSUE THREAD

**Issue by bgoodwin** [springbok/smerf#1]
I discovered this issue in SMERF version 0.0.1, but it might exist in the current version, too. 

When I have a question whose code is numeric (eg: "code: 1" ), questions are presented and answers are collected with no problem. However, if I then add validate_mandatory_question validation to that question, the validation _always_ fails. 

I traced the problem down to smerf/lib/smerf_system_helpers.rb. SmerfSystemHelpers::smerf_question_answered? performs the following tests:
responses.has_key?(question.code) and !responses[question.code].blank?()
In the scope of the smerf_question_answered? method, 'question' is a db representation of a question (smerf/app/models/smerf_question.rb) and question.code is returning a Numeric. 'responses', however, is a hash pulled straight from the http request so all its keys are Strings. Therefore responses will never have a numeric key and responses.has_key?(question.code) always returns false. 

Using a non-numeric question code in the yml reliably works around the issue.

**Comment by springbok** [comment]
Thank you for reporting the bug, this has now been addressed in the latest version. For the fix to take effect you need to make a change to your yaml files to force a reload, SMERF will then store all codes as string in the DB.
